// Generated by CoffeeScript 1.3.3
(function() {
  var DelayedOp, exports,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  DelayedOp = (function() {

    function DelayedOp(callback) {
      this.callback = callback;
      this.ready = __bind(this.ready, this);

      this.ok = __bind(this.ok, this);

      this.wait = __bind(this.wait, this);

      this.count = 1;
    }

    DelayedOp.prototype.wait = function() {
      return this.count++;
    };

    DelayedOp.prototype.ok = function() {
      if (!--this.count) {
        return this.callback();
      }
    };

    DelayedOp.prototype.ready = function() {
      return this.ok();
    };

    return DelayedOp;

  })();

  exports = this;

  exports.DelayedOp = DelayedOp;

}).call(this);
