// Generated by CoffeeScript 1.3.3
(function() {

  window.successURL = "https://www.facebook.com/connect/login_success.html";

  window.onFacebookLogin = function() {
    console.log("onFacebookLogin called");
    if (!localStorage.accessToken) {
      return chrome.tabs.getAllInWindow(null, function(tabs) {
        var i, params, x;
        i = 0;
        while (i < tabs.length) {
          if (tabs[i].url.indexOf(successURL) === 0) {
            console.log("here", tabs[i]);
            params = tabs[i].url.split("#")[1];
            x = params.split("&")[0];
            localStorage.accessToken = x.split("=")[1];
            console.log(localStorage.accessToken);
            chrome.tabs.onUpdated.removeListener(onFacebookLogin);
            $("#loading").hide();
            chrome.tabs.remove(tabs[i].id);
            window.get_stream();
            window.get_wall();
            window.get_friends();
            window.get_me();
            return;
          }
          i++;
        }
      });
    }
  };

  window.update_ui_login = function(login) {
    if (login === true) {
      return console.log("login ui modifications");
    } else {
      return console.log("logout ui modifications");
    }
  };

  chrome.tabs.onUpdated.addListener(onFacebookLogin);

}).call(this);
